repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: docker/helm
      - id: check-added-large-files
        exclude: yarn.lock
      - id: check-json
        exclude: .vscode
      - id: check-symlinks
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "8e0d199f4004a7f226ed7974fc3883d9c702bded" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "5cefd5485aec8e7a361a21bf0ec8bc9db02eb3c9" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
