#docker-compose.yml
version: "3"
services:
  testing-worker:
    build:
      context: ../
      dockerfile: docker/Dockerfile.worker
    # TODO: figure out how to upload this to the docker repo
    image: rapidapi/testing-worker:latest
    # environment:
    #   BASE_URL: "https://rapidapi.com/testing"
    #   LOCATION_KEY: "example"
    #   LOCATION_SECRET: "52ff291fe47a0bb0ecb2c15eff49b1cd6d6dd17f"
    #   LOCATION_CONTEXT: "3793937"
    #   FREQUENCY: "2000"
    #   # POLLING_TIME_MAX:
    #   BATCH_SIZE: "100"
    deploy:
      restart_policy:
        condition: any
# To run:
# $ docker-compose run testing-worker
