name: Release and publishing version specific packages

on:
  pull_request:

jobs:
  node-run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "v14.15.4"
      - run: yarn install --frozen-lockfile
      - run: yarn jest
