name: Pull requests checks and branch specific package publishing

on:
  pull_request:

jobs:
  node-build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "v14.15.4"
      - run: echo "${{ toJson(${{ github.event) }}"
      # - uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN_NPM }}
      #     registry: https://registry.npmjs.org/
      #     tag:
      # - uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN_GITHUB }}
      #     registry: https://npm.pkg.github.com
      #     tag:
