name: Pull requests checks and branch specific package publishing

on:
  pull_request:

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "v14.15.4"
      - run: |
          echo "Comment on PR #${{ github.event.issue.number }}"
