name: Release package and upload zip to lambdas in production

on:
  push:
    branches:
      - master

jobs:
  node-run-tests:
    name: Run tests and create zip artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "v14.15.4"
      - run: yarn install --frozen-lockfile
      - run: yarn jest
      - run: yarn check-format
      - run: yarn lint
      # Build lambda zip
      - uses: ./.github/actions/build-zip
        with: 
          ACTIONS_ACCESS_KEY: ${{ secrets.ACTIONS_ACCESS_KEY }}
  
  lambda-upload-zip-to-aws:
    needs: [node-run-tests]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [
          {
            name: us-east-1,
            key: AWS-US-EAST-1
          },
          {
            name: us-west-2,
            key: AWS-US-WEST-2
          },
          {
            name: ap-east-1,
            key: AWS-AP-EAST-1
          },
          {
            name: ap-south-1, 
            key: AWS-AP-SOUTH-1
          },
          {
            name: ap-southeast-1,  
            key: AWS-AP-SOUTHEAST-1
          },
          {
            name: ap-northeast-1, 
            key: AWS-AP-NORTHEAST-1
          },
          {
            name: eu-central-1,  
            key: AWS-EU-CENTRAL-1
          },
          {
            name: eu-west-3, 
            key: AWS-EU-WEST-3
          },
          {
            name: sa-east-1,
            key: AWS-SA-EAST-1
          }
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/upload-lambda
        with: 
          ACTIONS_ACCESS_KEY: ${{ secrets.ACTIONS_ACCESS_KEY }}
          worker_env: >
            BASE_URL=https://rapidapi.com/testing,
            LOCATION_CONTEXT=Default,
            LOCATION_KEY=${{ matrix.region.key }},
            LOCATION_SECRET=${{ secrets.LOCATION_SECRET_PROD_DEFAULT }},
            WORKER_LOGGING=off,
            POLLING_TIME_MAX=5000,
            FREQUENCY=1000
          aws_access_key_id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
          aws_region: ${{ matrix.region.name }}
          function_name: rapidapi-prod-testing-worker

  npm-publish-package:
    if: "contains(github.event.head_commit.message, 'ci-publish-package')"
    needs: [node-run-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "v14.15.4"
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN_NPM }}
          registry: https://registry.npmjs.org/
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.ACTIONS_ACCESS_KEY }}
          registry: https://npm.pkg.github.com

  make-release:
    if: "contains(github.event.head_commit.message, 'ci-publish-package')"
    needs: [npm-publish-package]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "v14.15.4"
      - run: yarn install --frozen-lockfile
      - name: Get version number
        uses: ./.github/actions/get-version
        id: get_package_version
      - name: Create a Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-v${{ steps.get_package_version.outputs.package_version }}
          release_name: Release v${{ steps.get_package_version.outputs.package_version }}
          body: This release was generated for commit ${{ github.sha }}
          draft: false
          prerelease: false

  docker-build-push-worker:
    if: "contains(github.event.head_commit.message, 'ci-publish-package')"
    needs: [node-run-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.worker
          push: true
          tags: rapidapicloud/testing-worker:latest
  