name: Release and publishing version specific packages

on:
  push:
    branches:
      - master

jobs:
  node-build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "v14.15.4"
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN_NPM }}
          registry: https://registry.npmjs.org/
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN_GITHUB }}
          registry: https://npm.pkg.github.com
