name: Release and publishing version specific packages

on:
  push:
    branches:
      - staging

jobs:
  build-worker-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "v14.15.4"
      - run: echo "${{ toJson(${{ github.event) }}"
